### ISSUE TITLE
Syntax error in Misc.hs from Cabal install

### ISSUE THREAD

**Issue by declo32** [bkomuves/polynomial-algebra#1]
Failed to build polynomial-algebra-0.1.
    Build log (
    /home/declan/.cabal/logs/ghc-9.0.2/polynomial-algebra-0.1-431f5eaf352903853a75a9ebad699f53054b8e634c7b2987c1678b27733668ea.log
    ):
    Configuring library for polynomial-algebra-0.1..
    Preprocessing library for polynomial-algebra-0.1..
    Building library for polynomial-algebra-0.1..
    [ 1 of 24] Compiling Math.Algebra.Polynomial.FreeModule ( src/Math/Algebra/Polynomial/FreeModule.hs, dist/build/Math/Algebra/Polynomial/FreeModule.o, dist/build/Math/Algebra/Polynomial/FreeModule.dyn_o )
    [ 2 of 24] Compiling Math.Algebra.Polynomial.Misc ( src/Math/Algebra/Polynomial/Misc.hs, dist/build/Math/Algebra/Polynomial/Misc.o, dist/build/Math/Algebra/Polynomial/Misc.dyn_o )
    
    src/Math/Algebra/Polynomial/Misc.hs:250:21: error:
        Suffix occurrence of @. For an as-pattern, remove the leading whitespace.
        |
    250 |   gaps k ws@(w:t) cs@ ~(c:u) 
        |                     ^
    cabal: Failed to build polynomial-algebra-0.1. See the build log above for details.

**Comment by bkomuves** [comment]
Should be fixed now.

The space was there, because not having the space _also_ cause a parse error with older versions of GHC... Fortunately it seems parentheses are accepted by all versions.
